name = "Apr2Project"
uuid = "6bb73342-608a-41bd-a8dc-6a3c310b2e29"
version = "0.1.0"
authors = ["Gideon Simpson <gideon.simpson@gmail.com>"]

[deps]
Cassette = "7057c7e9-c182-5462-911a-8362d720325c"

[compat]
Cassette = "0.3.14"
